In [3]:
import torch

In [4]:
print('hia')

hia


In [5]:
embeds = [
    [0.43, 0.15, 0.89], # Your 
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one
    [0.05, 0.80, 0.55]  # step
]

In [6]:
inputs = torch.tensor(embeds)
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [7]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
# attn_scores_2 is row 1 ("journey") dotted with each other row 
for i, x_i in enumerate(inputs):
    # print(i, x_i)
    attn_scores_2[i] = torch.dot(x_i, query)
print("attn_scores_2:", attn_scores_2)
# attn_weights_2 is softmax of attn_scores_2
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("attn_weights_2:", attn_weights_2)
context_vec_2 = torch.zeros(query.shape) # tensor([0., 0., 0.])
# weight every input row by its attention weight
for i, x_i in enumerate(inputs):
    print("row num:", i, "weight:", attn_weights_2[i], "row:", x_i, "weighted row:", attn_weights_2[i] * x_i)
    context_vec_2 += attn_weights_2[i] * x_i
print("context_vec_2:", context_vec_2)

attn_scores_2: tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
attn_weights_2: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
row num: 0 weight: tensor(0.1385) row: tensor([0.4300, 0.1500, 0.8900]) weighted row: tensor([0.0596, 0.0208, 0.1233])
row num: 1 weight: tensor(0.2379) row: tensor([0.5500, 0.8700, 0.6600]) weighted row: tensor([0.1308, 0.2070, 0.1570])
row num: 2 weight: tensor(0.2333) row: tensor([0.5700, 0.8500, 0.6400]) weighted row: tensor([0.1330, 0.1983, 0.1493])
row num: 3 weight: tensor(0.1240) row: tensor([0.2200, 0.5800, 0.3300]) weighted row: tensor([0.0273, 0.0719, 0.0409])
row num: 4 weight: tensor(0.1082) row: tensor([0.7700, 0.2500, 0.1000]) weighted row: tensor([0.0833, 0.0270, 0.0108])
row num: 5 weight: tensor(0.1581) row: tensor([0.0500, 0.8000, 0.5500]) weighted row: tensor([0.0079, 0.1265, 0.0870])
context_vec_2: tensor([0.4419, 0.6515, 0.5683])


In [8]:
attn_scores = torch.empty(6,6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
      attn_scores[i, j] = torch.dot(x_i, x_j)
print("attn_scores:\n", attn_scores)
# equivalently, using matrix multiplication:
attn_scores = inputs @ inputs.T
print("attn_scores:\n", attn_scores)
attn_weights = torch.softmax(attn_scores, dim=-1)
print("attn_weights:\n", attn_weights)
all_context_vecs = attn_weights @ inputs
print("all_context_vecs:\n", all_context_vecs)

attn_scores:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
attn_scores:
 tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])
attn_weights:
 tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.

In [9]:
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

In [10]:
# queries, keys and values are all the same matrix?
queries = np.array(embeds)
keys = np.array(embeds)
values = np.array(embeds)

# attn_scores = np.matmul(embeds, keys.T)
attn_scores = tf.matmul(embeds, keys.T)

attn_weights = tf.keras.activations.softmax(attn_scores, axis=1)
print("attn_weights:\n", attn_weights)
all_context_vecs = tf.matmul(attn_weights, keys)
print("all_context_vecs:\n", all_context_vecs)

attn_weights:
 tf.Tensor(
[[0.20983477 0.20058146 0.19814923 0.12422822 0.12204872 0.14515767]
 [0.13854757 0.23789129 0.23327403 0.1239916  0.10818187 0.15811361]
 [0.1390076  0.23692146 0.23260194 0.12420439 0.1108002  0.15646443]
 [0.1435269  0.20739442 0.20455202 0.14619222 0.12629524 0.17203921]
 [0.15261085 0.19583869 0.19749065 0.13668668 0.18785891 0.12951429]
 [0.13847117 0.21836372 0.2127594  0.14204757 0.09880637 0.18955176]], shape=(6, 6), dtype=float32)
all_context_vecs:
 tf.Tensor(
[[0.44205943 0.59309864 0.57898915]
 [0.44186574 0.651482   0.56830883]
 [0.44312754 0.6495946  0.5670731 ]
 [0.43038973 0.6298281  0.55102706]
 [0.46710175 0.59099275 0.5265966 ]
 [0.4177245  0.6503232  0.5645352 ]], shape=(6, 3), dtype=float32)


In [11]:
x_2 = inputs[1]
print("x_2:", x_2)
d_in = inputs.shape[1] # input embedding size = 3
d_out = 2
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

x_2: tensor([0.5500, 0.8700, 0.6600])


In [15]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)

tensor([0.4306, 1.4551])


In [16]:
for i, v in enumerate(x_2):
  print(v, W_query[i])

tensor(0.5500) tensor([0.2961, 0.5166])
tensor(0.8700) tensor([0.2517, 0.6886])
tensor(0.6600) tensor([0.0740, 0.8665])


In [17]:
keys = inputs @ W_key
values = inputs @ W_value
print("keys.shape:", keys.shape)
print("values.shape:", values.shape)

keys.shape: torch.Size([6, 2])
values.shape: torch.Size([6, 2])


In [21]:
for i, key_i in enumerate(keys):
    # print(i, x_i)
    attn_scores_2[i] = torch.dot(key_i, query_2)
print("attn_scores_2:", attn_scores_2)
d_k = keys.shape[-1] # 2
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim=-1) # scale by 1/1.414
print("attn_weights_2:\n", attn_weights_2)
context_vec_2 = attn_weights_2 @ values
print("context_vec_2:\n", context_vec_2)

attn_scores_2: tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])
attn_weights_2:
 tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])
context_vec_2:
 tensor([0.3061, 0.8210])


In [23]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))
    def forward(self, x):
        queries = x @ self.W_query
        keys = x @ self.W_key
        values = x @ self.W_value
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**.5, dim=-1)
        context_vec = attn_weights @ values
        return context_vec
        

In [24]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out) # 3,2
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)
